"""对齐 Rust ``common`` 模块：常量与共享类型占位。"""

from __future__ import annotations

from typing import Any, TypeVar

T = TypeVar("T")
AnyResult = Any  # Rust: Result<T, Box<dyn Error + Send + Sync>>

DEFAULT_CONNECT_TIMEOUT = 10
DEFAULT_REQUEST_TIMEOUT = 60
DEFAULT_CHANNEL_SIZE = 1000
DEFAULT_MAX_DECODING_MESSAGE_SIZE = 10 * 1024 * 1024
DEFAULT_METRICS_WINDOW_SECONDS = 5
DEFAULT_METRICS_PRINT_INTERVAL_SECONDS = 10
SLOW_PROCESSING_THRESHOLD_US = 3000.0

__all__ = [
    "AnyResult",
    "DEFAULT_CONNECT_TIMEOUT",
    "DEFAULT_REQUEST_TIMEOUT",
    "DEFAULT_CHANNEL_SIZE",
    "DEFAULT_MAX_DECODING_MESSAGE_SIZE",
    "DEFAULT_METRICS_WINDOW_SECONDS",
    "DEFAULT_METRICS_PRINT_INTERVAL_SECONDS",
    "SLOW_PROCESSING_THRESHOLD_US",
]
