# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import shredstream_pb2 as shredstream__pb2


class ShredstreamProxyStub(object):
    """与 Rust `shredstream/proto/mod.rs` 内嵌定义一致；路径 /shredstream.ShredstreamProxy/SubscribeEntries
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeEntries = channel.unary_stream(
                '/shredstream.ShredstreamProxy/SubscribeEntries',
                request_serializer=shredstream__pb2.SubscribeEntriesRequest.SerializeToString,
                response_deserializer=shredstream__pb2.Entry.FromString,
                _registered_method=True)


class ShredstreamProxyServicer(object):
    """与 Rust `shredstream/proto/mod.rs` 内嵌定义一致；路径 /shredstream.ShredstreamProxy/SubscribeEntries
    """

    def SubscribeEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShredstreamProxyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeEntries': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEntries,
                    request_deserializer=shredstream__pb2.SubscribeEntriesRequest.FromString,
                    response_serializer=shredstream__pb2.Entry.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shredstream.ShredstreamProxy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shredstream.ShredstreamProxy', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShredstreamProxy(object):
    """与 Rust `shredstream/proto/mod.rs` 内嵌定义一致；路径 /shredstream.ShredstreamProxy/SubscribeEntries
    """

    @staticmethod
    def SubscribeEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/shredstream.ShredstreamProxy/SubscribeEntries',
            shredstream__pb2.SubscribeEntriesRequest.SerializeToString,
            shredstream__pb2.Entry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
